config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/search'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/clothing_type.rb
class ClothingType < ActiveRecord::Base
end

app/models/parser.rb
class Parser
  include ActiveModel::Model

  attr_reader :input, :raw_input

  def initialize(input = "")
    @input = input
    @raw_input = input.clone
    process
  end

  def process
    replace_brands
    replace_clothing_types
  end

  def replace_brands
    brands.each do |brand|
      expresion = create_regexp_word(brand, 'b')
      replacement = create_html_word(brand,'b')
      @raw_input.gsub!(expresion,replacement)
    end
  end

  def replace_clothing_types
    clothing_types.each do |clothing_type|
      expresion = create_regexp_word(clothing_type, 'i')
      replacement = create_html_word(clothing_type,'i')
      @raw_input.gsub!(expresion,replacement)
    end
  end

  private

  def create_regexp_word(name,tag)
    Regexp.new("(?!(<#{tag}>))?(?<=\s|^)#{name}(?=\s|$)(?!(<\/#{tag}>))","i")
  end

  def create_html_word(name, tag)
    "<#{tag}>#{name}</#{tag}>"
  end

  def replace_with_italic(name)
    "<i>#{name}</i>"
  end

  def replace_with_bold(name)
    "<b>#{name}</b>"
  end

  def clothing_types
    ClothingType.pluck(:name).sort { |name| name.split(' ').length }
  end

  def brands
    Brand.pluck(:name).sort { |name| name.split(' ').length }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @parser = Parser.new
  end

  def search
    @parser = Parser.new(params_parse)
  end

  private

  def params_parse
    filtered = params.require(:parser).permit(:input)
    filtered[:input]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_form.slim
= form_for( parser, url: home_search_path, html: { method: 'GET' }) do |f|
  = f.label :input
  = f.text_field :input

  = f.button

app/views/home/index.slim
= render partial: 'form', locals: {parser: @parser}

app/views/home/search.slim
= render partial: 'form', locals: {parser: @parser}
p= @parser.raw_input.html_safe

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rokk3r</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>